all:
	g++ -c utils.cpp
	g++ -o 1_k_maior 1_k_maior.cpp utils.o
	g++ -o 2_sao_anagramas 2_sao_anagramas.cpp utils.o
	g++ -o 3_ordenar_alunos 3_ordenar_alunos.cpp utils.o
	g++ -o 4_remover_duplicatas 4_remover_duplicatas.cpp utils.o
	g++ -o 5_strings_por_tamanho 5_strings_por_tamanho.cpp utils.o
	g++ -o 6_quadro_medalhas 6_quadro_medalhas.cpp utils.o
